#!/usr/bin/python3
''' List of codepoints that we know we have images for (in ranges, because that's more compact),
    to make it easy for the app to avoid making broken image links.

    Meant to be used as ./generate-uci-have > uci_have.py whenever you change that image set.
''' 

import os
path = '/var/www/html/uci'

codepoints = []

l = os.listdir(path)
for fn in l:
    codepoints.append( int(fn.split('.',1)[0], 16) )


# Turn that into ranges, because it's smaller
#   I once found a smart oneliner, but this works.
scp = sorted(codepoints)
ranges = []
range_end = range_start = prev = scp.pop(0)
for v in scp:
    if v == prev+1:
        range_end = v
    else: # break; write out previous range and start new one
        ranges.append( (range_start, range_end) )
        range_start = range_end = v
    prev = v
ranges.append( (range_start, range_end) )


print( 'data = %s'%ranges )