#!/usr/bin/python3
#
# creates render-output/<codepoint>_fontname.png for all codepoints present in the
#
# https://fontforge.org/docs/scripting/python/fontforge.html#font

import glob,sys,os,gc
import fontforge

if not os.path.exists('render-output'): # implicitly under working directory
    os.mkdir('render-output')
    
for fontfn in sys.argv[1:]:

    fontbasename = os.path.basename( fontfn ).rsplit('.',1)[0]  # ...why am I not using the name fontforge resports? (better uniqueness maybe?)

    font = fontforge.open(fontfn)

    for glyph in font.glyphs(): # iterate through the present glyphs
        cpi = glyph.unicode #codepoint
        if cpi!=-1:
            cphex = '%06x'%glyph.unicode

            efn = os.path.join('render-output','%s_%s.png'%(cphex,fontbasename))   # hexcodepoint_fontfilename.png
            #print efn
            if not os.path.exists(efn):
                 print( 'export %s'%efn )
                 glyph.export(efn)
